twitter_url: http://twitter.com/EngineYard
facebook_url: http://www.facebook.com/engineyard

newsletter:
  post_url: http://engineyard.createsend.com/t/y/s/dhijjh/
  email_field_id: dhijjh-dhijjh
  email_field_name: cm-dhijjh-dhijjh
